server:
  port: 8080
spring:
  datasource:
    url: jdbc:mysql://inventory-management.cgt7lz1sc6lg.ap-southeast-1.rds.amazonaws.com:3306/inventory_system
    username: admin
    password: 5AAm7g6nyaPwSfncHoD5
  jpa:
    hibernate:
      ddl-auto: update
    show-sql: false
    properties:
      hibernate:
        dialect: org.hibernate.dialect.MySQL5InnoDBDialect
        format_sql: false

  security:
    oauth2:
      client:
        registration:
          google:
            clientId: 431784312354-qpof1fqpipodccdr7pi4amitoisr2h49.apps.googleusercontent.com
            clientSecret: gPVHuGBgH5JtoCM4S62Fqsty
            redirectUri: "{baseUrl}/oauth2/callback/{registrationId}"
            scope:
              - email
              - profile
app:
  oauth2:
    authorizedRedirectUris:
      - https://inventory-mng-system.com//oauth2/redirect
  hostName: https://inventory-mng-system.com
  fileImagePath: /var/data/product-img/
#logging:
#  level:
#    root: ERROR
#    org.springframework.web: DEBUG
#    com.project.inventory.webSecurity.aoth2.successHandler: DEBUG
#    org.hibernate: DEBUG
#    org: INFO
